//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace фабрика_на_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Заказные_изделия = new HashSet<Заказные_изделия>();
        }
    
        public int номер { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public int Этап_выполнения { get; set; }
        public string заказчик { get; set; }
        public string менеджер { get; set; }
        public decimal стоимость { get; set; }
        public string Артикул_используемой_фурнитуры { get; set; }
        public string Артикул_используемой_ткани { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Текущий_этап_выполнения Текущий_этап_выполнения { get; set; }
        public virtual Ткани Ткани { get; set; }
        public virtual Фурнитура Фурнитура { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказные_изделия> Заказные_изделия { get; set; }
    }
}
