//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace фабрика_на_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделия_созданные_заказчиками
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public decimal ширина { get; set; }
        public decimal длина { get; set; }
        public string заказчик { get; set; }
        public int спецификация { get; set; }
    }
}
