//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace фабрика_на_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставки()
        {
            this.Склад_ткани = new HashSet<Склад_ткани>();
            this.Склад_фунитуры = new HashSet<Склад_фунитуры>();
        }
    
        public int ID_Поставки { get; set; }
        public string Поставщик { get; set; }
        public string Артикул { get; set; }
        public string Название { get; set; }
        public int Колличетво { get; set; }
        public decimal Цена { get; set; }
        public decimal Сумма { get; set; }
        public int Тип { get; set; }
    
        public virtual Поставщик_ткани Поставщик_ткани { get; set; }
        public virtual Поставщик_Фурнитуры Поставщик_Фурнитуры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад_ткани> Склад_ткани { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад_фунитуры> Склад_фунитуры { get; set; }
    }
}
