//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace фабрика_на_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ткани
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ткани()
        {
            this.Заказ = new HashSet<Заказ>();
            this.Остатки_тканей = new HashSet<Остатки_тканей>();
            this.Изделия = new HashSet<Изделия>();
        }
    
        public string Артикул { get; set; }
        public string Название { get; set; }
        public string Цвет { get; set; }
        public string Рисунок { get; set; }
        public string Состав { get; set; }
        public decimal Ширина { get; set; }
        public decimal Длина { get; set; }
        public decimal Цена { get; set; }
        public byte[] Изображене { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Остатки_тканей> Остатки_тканей { get; set; }
        public virtual Склад_ткани Склад_ткани { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Изделия> Изделия { get; set; }
    }
}
