//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace фабрика_на_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фурнитура_изделия
    {
        public string Артикул_фурнитуры { get; set; }
        public string Артикул_изделия { get; set; }
        public string Рзмещение { get; set; }
        public Nullable<decimal> Ширина { get; set; }
        public Nullable<decimal> Длина { get; set; }
        public Nullable<int> Поворот { get; set; }
        public int Колличетво { get; set; }
    
        public virtual Изделия Изделия { get; set; }
        public virtual Фурнитура Фурнитура { get; set; }
    }
}
